<!DOCTYPE html>
<html>
    <head>
  <title> 我的小世界 </title>
        </head>
    <body>
      <p style="color:green"> 域名网站
          </p>
          <a href="https://byet.host"> Byet.Host </a> 
    <a style=“color:blue;font-size:160%;margin-left:20px;”>     <a href="https://www.baidu.com"> baidu </a> </a>
    
   <p title="运行百度"> baidu </p>
        
        
<b>域名网站</b><div>百度 - wwww.baidu.com&nbsp;</div><div>优酷 - www.youku.com</div><div><br></div><div><b><br></b></div>
        <div>在线HTML 编辑器 - admission.ucas.ac.cn&nbsp;</div><div>html讨论 - www.w3schools.com</div><div><br></div><div><b><br></b></div>
          
        body
{
background-image:url('beijin.jpg');
background-repeat:repeat-x;
}
    </body>
    
    </html>
